function openNav() {
   document.getElementById("mySidenav").style.width = "30%";
}
function closeNav() {
   document.getElementById("mySidenav").style.width = "0";
}
function UpdateInput1(val) {
   document.getElementById('inputNumber1').value = val;
}
function UpdateInput2(val) {
   document.getElementById('inputNumber2').value = val;
}
function UpdateInput3(val) {
   document.getElementById('inputNumber3').value = val;
}
function UpdateInput4(val) {
   document.getElementById('inputNumber4').value = val;
}